site_name: Wiki
site_author: nitsua
site_description: Notifiarr provides native custom integrations with dozens of applications and websites. That means these applications or websites can send data to Notifiarr, and we’ll format a message according to your configuration then send it to your chat server.
site_url: http://rm-web-1:8007/en/latest/
repo_name: Client
repo_url: https://github.com/Notifiarr/notifiarr


nav:
  - Notifiarr:
    - About: index.md
  - Quick Start:
    - Quick Start: pages/quickstart/quickStart.md
  - Client:
    - Install: pages/client/install.md
    - Config: pages/client/configuration.md
    - GUI: pages/client/gui.md
    - Cloudflare config: pages/client/cloudflare.md
    - Reverse proxy: pages/client/reverseProxy.md
    - Setup: pages/client/setup.md
  - Website:
    - Client config: pages/website/clientConfig.md
    - Integrations setup: pages/website/integrationsSetup.md
    - Media requests: pages/website/mediaRequests.md
    - Notification history: pages/website/notificationHistory.md
    - Transcode history: pages/website/transcodeHistory.md
    - Trending: pages/website/trending.md
    - Translations: pages/website/translations.md
    - Metrics: pages/website/metrics.md
  - Integrations:
    - How To Setup Integrations: pages/integrations/basicUsage.md
    - Authentik: pages/integrations/authentik.md
    - Bazarr: pages/integrations/bazarr.md
    - Better Stack: pages/integrations/betterstack.md
    - Dashboard: pages/integrations/dashboard.md
    - Discord App: pages/integrations/discordApp.md
    - Emby: pages/integrations/emby.md
    - Github: pages/integrations/github.md
    - Hotio: pages/integrations/hotio.md
    - Jellyfin: pages/integrations/jellyfin.md
    - Lidarr: pages/integrations/lidarr.md
    - Log Watcher: pages/integrations/logWatch.md
    - Media Requests: pages/integrations/mediaRequests.md
    - MDBList: pages/integrations/mdblist.md
    - Network: pages/integrations/network.md
    - Passthrough: pages/integrations/passthrough.md
    - Persistent: pages/integrations/persistent.md
    - Plex: pages/integrations/plex.md
    - Plex Meta Manager: pages/integrations/plexmetamanager.md
    - Overseerr: pages/integrations/overseerr.md
    - Radarr: pages/integrations/radarr.md
    - Readarr: pages/integrations/readarr.md
    - Release Parser: pages/integrations/releaseParser.md
    - Reddit: pages/integrations/reddit.md
    - RSS Watcher: pages/integrations/rssWatcher.md
    - Simon Says: pages/integrations/simonSays.md
    - Snapshots: pages/integrations/snapshots.md
    - Sonarr: pages/integrations/sonarr.md
    - TRaSH: pages/integrations/trash.md
    - Unpackerr: pages/integrations/unpackerr.md
    - Website Status: pages/integrations/websitestatus.md
  - Discord Bot:
    - Permissions: pages/discordbot/permissions.md
    - Custom Bot: pages/discordbot/custombot.md
  - Translations:
    - Contribute: pages/translations/contribute.md
  - Faq: 
    - Faq: pages/faq/faq.md



theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.png
  favicon: assets/favicon.ico
  language: en
  features:
    - content.code.annotate
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.tooltips
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.instant
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
  
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/weather-sunny
        name: Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/weather-night
        name: Dark mode
plugins:
   - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       width: 100%
       height: auto
       zoomable: true
       draggable: true
       auto_caption: false
       caption_position: bottom


markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html

